export const metadata = {
  title: "Affiliate Disclosure | Travel RAG Search Engine",
  description: "FTC-required affiliate disclosure for Travel RAG Search Engine.",
};

export default function DisclosurePage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-12 prose prose-neutral">
      <h1>Affiliate Disclosure</h1>
      <p className="text-sm text-gray-500">Last updated: March 2026</p>

      <p>
        Travel RAG Search Engine participates in affiliate marketing programs.
        This means we may earn a commission when you click on certain links and
        make a purchase or sign up for a service — at no additional cost to you.
      </p>

      <h2>Our Affiliate Partners</h2>
      <ul>
        <li>
          <strong>Booking.com</strong> — We earn a commission on hotel bookings
          made through our links.
        </li>
        <li>
          <strong>Klook</strong> — We earn a commission on activity and
          experience bookings made through our links.
        </li>
        <li>
          <strong>Wise</strong> — We earn a referral fee when new customers
          sign up for Wise and make their first transfer through our links.
        </li>
      </ul>

      <h2>How We Select Recommendations</h2>
      <p>
        Affiliate relationships do not influence the AI responses generated by
        our search engine. Travel recommendations are based solely on relevance
        to your query. Affiliate links are added contextually after the answer
        is generated.
      </p>

      <h2>FTC Compliance</h2>
      <p>
        This disclosure is made in accordance with the U.S. Federal Trade
        Commission&apos;s guidelines on endorsements and testimonials (16 CFR Part
        255). Every response that includes an affiliate link includes an inline
        disclosure statement.
      </p>

      <h2>Questions</h2>
      <p>
        For questions about our affiliate relationships, email{" "}
        <a href="mailto:hello@travelrag.app">hello@travelrag.app</a>.
      </p>
    </main>
  );
}
