export const metadata = {
  title: "Terms of Service | Travel RAG Search Engine",
  description: "Terms and conditions for using Travel RAG Search Engine.",
};

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-12 prose prose-neutral">
      <h1>Terms of Service</h1>
      <p className="text-sm text-gray-500">Last updated: March 2026</p>

      <h2>1. Acceptance</h2>
      <p>
        By using Travel RAG Search Engine (&quot;the Service&quot;), you agree to these
        terms. If you do not agree, do not use the Service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        Travel RAG Search Engine is an AI-powered travel Q&amp;A tool that provides
        information about travel destinations including Japan, Thailand, Italy,
        Turkey, and South Korea. Answers are generated by AI and may contain
        errors. Always verify critical travel information with official sources.
      </p>

      <h2>3. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for automated scraping or bulk queries</li>
        <li>Attempt to reverse-engineer or circumvent rate limiting</li>
        <li>Use the Service for any unlawful purpose</li>
      </ul>

      <h2>4. Affiliate Links</h2>
      <p>
        The Service may include affiliate links to travel booking platforms. We
        earn a commission when you make a purchase through these links at no
        extra cost to you. See our <a href="/disclosure">Affiliate Disclosure</a>{" "}
        for details.
      </p>

      <h2>5. Disclaimer of Warranties</h2>
      <p>
        The Service is provided &quot;as is&quot; without warranties of any kind. AI
        responses may be inaccurate, incomplete, or outdated. We are not
        responsible for travel decisions made based on the Service.
      </p>

      <h2>6. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, we are not liable for any
        indirect, incidental, or consequential damages arising from your use of
        the Service.
      </p>

      <h2>7. Changes to Terms</h2>
      <p>
        We may update these terms at any time. Continued use of the Service
        after changes constitutes acceptance.
      </p>

      <h2>8. Contact</h2>
      <p>
        For questions about these terms, email{" "}
        <a href="mailto:legal@travelrag.app">legal@travelrag.app</a>.
      </p>
    </main>
  );
}
